### ISSUE TITLE
try to send transfer tx in multisig way but appears Translating error Error: Signature verification failed

### ISSUE THREAD

**Issue by tpkeeper** [project-serum/multisig#11]
here is main code 
```
    const data = anchor.web3.SystemProgram.transfer({
      fromPubkey: multisigSigner,
      toPubkey: ownerA.publicKey,
      lamports: new anchor.BN(1000000000),
    }).data
    const transferPid = anchor.web3.SystemProgram.programId

    const transaction = anchor.web3.Keypair.generate();
    const txSize = 1000; // Big enough, cuz I'm lazy.
    await program.rpc.createTransaction(transferPid, accounts, data, {
      accounts: {
        multisig: multisig.publicKey,
        transaction: transaction.publicKey,
        proposer: ownerA.publicKey,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      },
      instructions: [
        await program.account.transaction.createInstruction(
          transaction,
          txSize
        ),
      ],
      signers: [transaction],
    });

```

```
await program.rpc.executeTransaction({
      accounts: {
        multisig: multisig.publicKey,
        multisigSigner,
        transaction: transaction.publicKey,
      },
      remainingAccounts:
        [{
          pubkey: multisig.publicKey,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: anchor.web3.SystemProgram.programId,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: multisigSigner,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: ownerA.publicKey,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: program.programId,
          isWritable: true,
          isSigner: false,
        }],
    });
```

**Comment by armaniferrante** [comment]
Hard to tell without seeing the omitted code, but if `ownerA` is not part of the provider, then you need to pass the keypair to the `signers` array.

**Comment by tpkeeper** [comment]
thanks and this is all the test code
```
const anchor = require("@project-serum/anchor");
const assert = require("assert");

describe("multisig test", () => {
  // Configure the client to use the local cluster.
  let provider = anchor.Provider.env()
  anchor.setProvider(provider);

  const program = anchor.workspace.Multisig;


  it("Tests the multisig program", async () => {
    // const myAccount = new anchor.web3.Keypair.fromSecretKey(
    //   [179,95,213,234,125,167,246,188,230,134,181,219,31,146,239,75,190,124,112,93,187,140,178,119,90,153,207,178,137,5,53,71,116,28,190,12,249,238,110,135,109,21,196,36,191,19,236,175,229,204,68,180,130,102,71,239,41,53,152,159,175,124,180,6]
    // );

    const localAccount = anchor.web3.Keypair.fromSecretKey(
      new Uint8Array([179, 95, 213, 234, 125, 167, 246, 188, 230, 134, 181, 219, 31, 146, 239, 75, 190, 124, 112, 93, 187, 140, 178, 119, 90, 153, 207, 178, 137, 5, 53, 71, 116, 28, 190, 12, 249, 238, 110, 135, 109, 21, 196, 36, 191, 19, 236, 175, 229, 204, 68, 180, 130, 102, 71, 239, 41, 53, 152, 159, 175, 124, 180, 6])
    )
    console.log("myAccount:", localAccount.publicKey.toString());

    const multisig = anchor.web3.Keypair.generate();
    console.log("multisig:", multisig.publicKey.toString());
    const [
      multisigSigner,
      nonce,
    ] = await anchor.web3.PublicKey.findProgramAddress(
      [multisig.publicKey.toBuffer()],
      program.programId
    );
    const multisigSize = 200; // Big enough.

    const ownerA = anchor.web3.Keypair.generate();
    const ownerB = anchor.web3.Keypair.generate();
    const ownerC = anchor.web3.Keypair.generate();
    const ownerD = anchor.web3.Keypair.generate();
    const owners = [ownerA.publicKey, ownerB.publicKey, ownerC.publicKey];
    console.log("ownerA:", ownerA.publicKey.toString());
    console.log("ownerB:", ownerB.publicKey.toString());
    console.log("ownerC:", ownerC.publicKey.toString());
    console.log("multiSigner:", multisigSigner.toString());

    const threshold = new anchor.BN(2);
    await program.rpc.createMultisig(owners, threshold, nonce, {
      accounts: {
        multisig: multisig.publicKey,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      },
      instructions: [
        await program.account.multisig.createInstruction(
          multisig,
          multisigSize
        ),
      ],
      signers: [multisig],
    });

    let multisigAccount = await program.account.multisig(multisig.publicKey);

    assert.equal(multisigAccount.nonce, nonce);
    assert.ok(multisigAccount.threshold.eq(new anchor.BN(2)));
    assert.deepEqual(multisigAccount.owners, owners);

    // const pid = program.programId;
    const accounts = [
      {
        pubkey: multisig.publicKey,
        isWritable: true,
        isSigner: false,
      },
      {
        pubkey: multisigSigner,
        isWritable: false,
        isSigner: true,
      },
    ];
    // const newOwners = [ownerA.publicKey, ownerB.publicKey, ownerD.publicKey];
    // const data = program.coder.instruction.encode('set_owners', {
    //   owners: newOwners,
    // });
    await transfer(provider, localAccount.publicKey, multisigSigner, localAccount)

    const data = anchor.web3.SystemProgram.transfer({
      fromPubkey: multisigSigner,
      toPubkey: ownerA.publicKey,
      lamports: new anchor.BN(1000000000),
    }).data
    const transferPid = anchor.web3.SystemProgram.programId

    const transaction = anchor.web3.Keypair.generate();
    const txSize = 1000; // Big enough, cuz I'm lazy.
    await program.rpc.createTransaction(transferPid, accounts, data, {
      accounts: {
        multisig: multisig.publicKey,
        transaction: transaction.publicKey,
        proposer: ownerA.publicKey,
        rent: anchor.web3.SYSVAR_RENT_PUBKEY,
      },
      instructions: [
        await program.account.transaction.createInstruction(
          transaction,
          txSize
        ),
      ],
      signers: [transaction],
    });

    const txAccount = await program.account.transaction(transaction.publicKey);

    assert.ok(txAccount.programId.equals(transferPid));
    assert.deepEqual(txAccount.accounts, accounts);
    assert.deepEqual(txAccount.data, data);
    assert.ok(txAccount.multisig.equals(multisig.publicKey));
    assert.equal(txAccount.didExecute, false);

    // Other owner approves transactoin.
    await program.rpc.approve({
      accounts: {
        multisig: multisig.publicKey,
        transaction: transaction.publicKey,
        owner: ownerB.publicKey,
      },
      signers: [ownerB],
    });

    // Now that we've reached the threshold, send the transactoin.
    await program.rpc.executeTransaction({
      accounts: {
        multisig: multisig.publicKey,
        multisigSigner,
        transaction: transaction.publicKey,
      },
      remainingAccounts:
        [{
          pubkey: multisig.publicKey,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: anchor.web3.SystemProgram.programId,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: multisigSigner,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: ownerA.publicKey,
          isWritable: true,
          isSigner: false,
        }, {
          pubkey: program.programId,
          isWritable: true,
          isSigner: false,
        }],
    });

    // multisigAccount = await program.account.multisig(multisig.publicKey);

    // assert.equal(multisigAccount.nonce, nonce);
    // assert.ok(multisigAccount.threshold.eq(new anchor.BN(2)));
    // assert.deepEqual(multisigAccount.owners, newOwners);
  });
});



async function transfer(provider, from, to, authority) {

  const instructions = [anchor.web3.SystemProgram.transfer({
    fromPubkey: from,
    toPubkey: to,
    lamports: new anchor.BN(2000000000),
  }),
  ]

  const tx = new anchor.web3.Transaction();
  tx.add(...instructions);

  await provider.send(tx, [authority]);
  return;
}
```

**Comment by tpkeeper** [comment]
and the log
```
Program Id: CqGkbeAMkkgbMgny4U1EJDysVvh13ueMs1HkaAMghedW

Deploy success


  multisig
myAccount: 8pFiM2vyEzyYL7oJqaK2CgHPnARFdziM753rDHWsnhU1
multisig: 82syMWxg8Mf5KgqGE3qkotJ6kCC83DcbJy1LG14otF1u
ownerA: GkWMciK4UedtQbWb6tLaXnb6GrqunGCgG82t51buAg9r
ownerB: 8eWLYW6ST7rjJBdwsQUVXBdu2u1s18Jsu4TBZRCsTRoJ
ownerC: Bmrx1iB3brFPW3HiUinEpBpGxGHCkGidx1KjUJpwsYJv
multiSigner: HzydjpFnLkU3KUYdnvoHGsh2cfVyEQ4j97S3GHy6Q1ya
Translating error Error: Signature verification failed
    at Transaction.serialize (/Users/tpkeeper/rustwork/multisig/node_modules/@solana/web3.js/lib/index.cjs.js:1105:13)
    at Provider.send (/Users/tpkeeper/rustwork/multisig/node_modules/@project-serum/anchor/dist/cjs/provider.js:80:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Object.rpc [as createTransaction] (/Users/tpkeeper/rustwork/multisig/node_modules/@project-serum/anchor/dist/cjs/namespace/rpc.js:12:31)
    at async Context.<anonymous> (/Users/tpkeeper/rustwork/multisig/tests/multisig.js:92:5)
    1) Tests the multisig program


  0 passing (2s)
  1 failing

  1) multisig
       Tests the multisig program:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by armaniferrante** [comment]
Did you try adding `ownerA` to the `signers` array?

**Comment by tpkeeper** [comment]
after try adding ownerA to

**Comment by tpkeeper** [comment]
after adding ownerA to  signers array of `program.rpc.executeTransaction`, it print this
```
Deploying workspace: https://devnet.solana.com
Upgrade authority: /Users/tpkeeper/.config/solana/id.json
Deploying program "multisig"...
Program path: /Users/tpkeeper/rustwork/multisig/target/deploy/multisig.so...
Program Id: 5Hzq9dLTa1ZjoUeQQk1WgUSHJKaibA72epk4JCvHUKCt

Deploy success


  multisig test
myAccount: 8pFiM2vyEzyYL7oJqaK2CgHPnARFdziM753rDHWsnhU1
multisig: H3W2tZLNMPZZw87sQMHoDgiCcJTJqUZD2s5xXB3YBMTD
ownerA: DVLfsqzJD3mRjGAQbAJtZBisn7ba1on7MM482WJLmKUF
ownerB: EkfGSVwQT6KGQhQxN7zktn6rXVYk6qxp6P9WLUcm8e3d
ownerC: 4kRTBstJnNdZT6HairYLYpWT7XG2ut6Skt18gt5bBG35
multiSigner: A4fWSVcgaTsBwn5oCJZ5NRvS5T986s85CiXt3En52sPN
approve finish
Transaction references a signature that is unnecessary, only the fee payer and instruction signer accounts should sign a transaction. This behavior is deprecated and will throw an error in the next major version release.
Transaction references a signature that is unnecessary, only the fee payer and instruction signer accounts should sign a transaction. This behavior is deprecated and will throw an error in the next major version release.
Transaction references a signature that is unnecessary, only the fee payer and instruction signer accounts should sign a transaction. This behavior is deprecated and will throw an error in the next major version release.
Transaction simulation failed: Error processing Instruction 0: missing required signature for instruction 
    Program 5Hzq9dLTa1ZjoUeQQk1WgUSHJKaibA72epk4JCvHUKCt invoke [1]
    Program 11111111111111111111111111111111 invoke [2]
    Transfer: `from` account H3W2tZLNMPZZw87sQMHoDgiCcJTJqUZD2s5xXB3YBMTD must sign
    Program 11111111111111111111111111111111 failed: missing required signature for instruction
    Program 5Hzq9dLTa1ZjoUeQQk1WgUSHJKaibA72epk4JCvHUKCt consumed 200000 of 200000 compute units
    Program 5Hzq9dLTa1ZjoUeQQk1WgUSHJKaibA72epk4JCvHUKCt failed: missing required signature for instruction
Translating error Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: missing required signature for instruction
    at Connection.sendEncodedTransaction (/Users/tpkeeper/rustwork/multisig/node_modules/@solana/web3.js/lib/index.cjs.js:4571:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Connection.sendRawTransaction (/Users/tpkeeper/rustwork/multisig/node_modules/@solana/web3.js/lib/index.cjs.js:4532:20)
    at async Object.sendAndConfirmRawTransaction (/Users/tpkeeper/rustwork/multisig/node_modules/@solana/web3.js/lib/index.cjs.js:6314:21)
    at async Provider.send (/Users/tpkeeper/rustwork/multisig/node_modules/@project-serum/anchor/dist/cjs/provider.js:81:22)
    at async Object.rpc [as executeTransaction] (/Users/tpkeeper/rustwork/multisig/node_modules/@project-serum/anchor/dist/cjs/namespace/rpc.js:12:31)
    at async Context.<anonymous> (/Users/tpkeeper/rustwork/multisig/tests/multisig.js:127:5)
    1) Tests the multisig program


  0 passing (4s)
  1 failing

  1) multisig test
       Tests the multisig program:
     Error: Promise rejected with no or falsy reason
      at processTicksAndRejections (internal/process/task_queues.js:93:5
```

**Comment by armaniferrante** [comment]
You're providing invalid accounts to your transaction

```
    const accounts = [
      {
        pubkey: multisig.publicKey,
        isWritable: true,
        isSigner: false,
      },
      {
        pubkey: multisigSigner,
        isWritable: false,
        isSigner: true,
      },
    ];
    ```
    
    The accounts must match the accounts you need for your instruction, in your case, 
    
    ```
    SystemProgram.transfer({
      fromPubkey: multisigSigner,
      toPubkey: ownerA.publicKey,
      lamports: new anchor.BN(1000000000),
    })
    ```
    
    Closing as this isn't related to development. For further help, please join the Discord.

**Comment by gibrangul95** [comment]
@tpkeeper were you able to get this transfer example running? I have the same problem

**Comment by congnghia0609** [comment]
I spent a lot of time writing this test case: **Tests the multisig program tranfer SOL**. Hopefully the next ones will have less effort.
```rust
const LAMPORTS_PER_SOL = 1000000000;

it("Tests the multisig program tranfer SOL", async () => {
    const multisig = anchor.web3.Keypair.generate();
    const [multisigSigner, nonce] =
      await anchor.web3.PublicKey.findProgramAddress(
        [multisig.publicKey.toBuffer()],
        program.programId
      );
    const multisigSize = 200; // Big enough.

    const payer = anchor.web3.Keypair.generate();
    const ownerA = anchor.web3.Keypair.generate();
    const ownerB = anchor.web3.Keypair.generate();
    const ownerC = anchor.web3.Keypair.generate();
    const owners = [ownerA.publicKey, ownerB.publicKey, ownerC.publicKey];

    const threshold = new anchor.BN(2);
    console.log("Begin createMultisig");
    await program.rpc.createMultisig(owners, threshold, nonce, {
      accounts: {
        multisig: multisig.publicKey,
      },
      instructions: [
        await program.account.multisig.createInstruction(
          multisig,
          multisigSize
        ),
      ],
      signers: [multisig],
    });
    console.log("End createMultisig");

    let multisigAccount = await program.account.multisig.fetch(
      multisig.publicKey
    );
    assert.strictEqual(multisigAccount.nonce, nonce);
    assert.ok(multisigAccount.threshold.eq(new anchor.BN(2)));
    assert.deepStrictEqual(multisigAccount.owners, owners);
    assert.ok(multisigAccount.ownerSetSeqno === 0);

    let multisigSignerAmount = await provider.connection.getBalance(multisigSigner);
    let ownerAAmount = await provider.connection.getBalance(ownerA.publicKey);
    assert.ok(multisigSignerAmount === 0);
    assert.ok(ownerAAmount === 0);
    // console.log("multisigSigner.publicKey:", multisigSigner.toBase58());
    // console.log("ownerA.publicKey:", ownerA.publicKey.toBase58());
    console.log(`multisigSigner: ${multisigSignerAmount / LAMPORTS_PER_SOL} SOL`);
    console.log(`ownerA: ${ownerAAmount / LAMPORTS_PER_SOL} SOL`);
    console.log("Begin transfer SOL to multisigSigner");
    // Airdrop Sol to payer.
    await provider.connection.confirmTransaction(
      await provider.connection.requestAirdrop(payer.publicKey, 100 * LAMPORTS_PER_SOL),
      "processed"
    );
    // Fund Sol to account multisigSigner.
    const amount = 10 * LAMPORTS_PER_SOL; // 1 sol = 10^9 lamports
    await provider.send(
      (() => {
        const tx = new anchor.web3.Transaction();
        tx.add(
          anchor.web3.SystemProgram.transfer({
            fromPubkey: payer.publicKey,
            toPubkey: multisigSigner,
            lamports: amount,
          }),
        );
        return tx;
      })(), 
      [payer]
    );
    console.log("End transfer SOL to multisigSigner");
    multisigSignerAmount = await provider.connection.getBalance(multisigSigner);
    ownerAAmount = await provider.connection.getBalance(ownerA.publicKey);
    assert.ok(multisigSignerAmount === amount);
    assert.ok(ownerAAmount === 0);
    console.log(`multisigSigner: ${multisigSignerAmount / LAMPORTS_PER_SOL} SOL`);
    console.log(`ownerA: ${ownerAAmount / LAMPORTS_PER_SOL} SOL`);

    const transferPid = anchor.web3.SystemProgram.programId;
    const accounts = [
      {
        pubkey: multisigSigner,
        isWritable: true,
        isSigner: true,
      },
      {
        pubkey: ownerA.publicKey,
        isWritable: true,
        isSigner: false,
      },
    ];
    const data = anchor.web3.SystemProgram.transfer({
      fromPubkey: multisigSigner,
      toPubkey: ownerA.publicKey,
      lamports: new anchor.BN(amount),
    }).data

    const transaction = anchor.web3.Keypair.generate();
    const txSize = 1000; // Big enough, cuz I'm lazy.
    console.log("Begin createTransaction");
    await program.rpc.createTransaction(transferPid, accounts, data, {
      accounts: {
        multisig: multisig.publicKey,
        transaction: transaction.publicKey,
        proposer: ownerA.publicKey,
      },
      instructions: [
        await program.account.transaction.createInstruction(
          transaction,
          txSize
        ),
      ],
      signers: [transaction, ownerA],
    });
    console.log("End createTransaction");

    const txAccount = await program.account.transaction.fetch(
      transaction.publicKey
    );
    assert.ok(txAccount.programId.equals(transferPid));
    assert.deepStrictEqual(txAccount.accounts, accounts);
    assert.deepStrictEqual(txAccount.data, data);
    assert.ok(txAccount.multisig.equals(multisig.publicKey));
    assert.deepStrictEqual(txAccount.didExecute, false);
    assert.ok(txAccount.ownerSetSeqno === 0);

    // Other owner approves transactoin.
    console.log("Begin approve");
    await program.rpc.approve({
      accounts: {
        multisig: multisig.publicKey,
        transaction: transaction.publicKey,
        owner: ownerB.publicKey,
      },
      signers: [ownerB],
    });
    console.log("End approve");

    // Now that we've reached the threshold, send the transactoin.
    console.log("Begin executeTransaction");
    await program.rpc.executeTransaction({
      accounts: {
        multisig: multisig.publicKey,
        multisigSigner,
        transaction: transaction.publicKey,
      },
      remainingAccounts:[
        {
          pubkey: multisigSigner,
          isWritable: true,
          isSigner: false,
        },
        {
          pubkey: ownerA.publicKey,
          isWritable: true,
          isSigner: false,
        },
        {
          pubkey: anchor.web3.SystemProgram.programId,
          isWritable: false,
          isSigner: false,
        },
      ],
      signers: [],
    });
    console.log("End executeTransaction");

    multisigSignerAmount = await provider.connection.getBalance(multisigSigner);
    ownerAAmount = await provider.connection.getBalance(ownerA.publicKey);
    assert.ok(multisigSignerAmount === 0);
    assert.ok(ownerAAmount === amount);
    console.log(`multisigSigner: ${multisigSignerAmount / LAMPORTS_PER_SOL} SOL`);
    console.log(`ownerA: ${ownerAAmount / LAMPORTS_PER_SOL} SOL`);

    multisigAccount = await program.account.multisig.fetch(multisig.publicKey);
    // console.log(multisigAccount);
    assert.strictEqual(multisigAccount.nonce, nonce);
    assert.ok(multisigAccount.threshold.eq(new anchor.BN(2)));
    assert.deepStrictEqual(multisigAccount.owners, owners);
    assert.ok(multisigAccount.ownerSetSeqno === 0);
  });
```
Have a nice day.
